server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false


# Increase the Hystrix timeout to 60s (globally) - not sure if that is solution
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


zuul:
  host:
    socket-timeout-millis: 60000
  debug:
    request: true
  routes:
    card-service:
      path: /card-service/**
      serviceId: card-service
      stripPrefix: false
    statement-service:
      path: /statement-service/**
      serviceId: statement-service
      stripPrefix: true
    card-statement-composite:
      path: /card-statement-composite/**
      serviceId: card-statement-composite
      stripPrefix: true
---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
    client:
      serviceUrl:
        defaultZone: http://discovery-service:8761/
