server:
  port: 0
turbine:
  amqp:
    port: 8989

---
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
# turbine:
#  appConfig: card-statement,card,statement
#   appConfig: card-statement
#   combineHostPort: true
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8989
